# ZINTERSTORE destination numkeys key [key ...] [WEIGHTS weight] [AGGREGATE SUM|MIN|MAX]

ZINTERSTORE z3 2 z1 z2 WEIGHTS 5 6 AGGREGATE SUM
ZINTERSTORE z3 2 z1 z2 WEIGHTS 5 6 AGGREGATE MAX
ZINTERSTORE z3 2 z1 z2 WEIGHTS 5 6 AGGREGATE MIN
